services:
  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - strapi-pg_data:/var/lib/postgresql/data/ #using a volume

    ports:
      - "5432:5432"
    networks:
      - strapi

volumes:
  strapi-pg_data:

networks:
  strapi:
    name: strapi
    driver: bridge