services:
  strapiDB-service:
    profiles: ["local", "remote", "prod"]
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - strapi-volume-pg_data:/var/lib/postgresql/data/ #using a volume
    ports:
      - "5432:5432"
    networks:
      - strapi-network

volumes:
  strapi-volume-pg_data:

networks:
  strapi-network:
    name: strapi-network
    driver: bridge
