services:
  strapi-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: strapi-local:latest
    restart: unless-stopped
    volumes:
      - ./public/uploads:/opt/app/public/uploads
    networks:
      - strapi-network
    depends_on:
      - strapiDB-service
    environment:
      DATABASE_HOST: strapiDB-service
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_S3_ACL: ${AWS_S3_ACL}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_SIGNED_URL_EXPIRES: ${AWS_SIGNED_URL_EXPIRES}

  ### LOCAL PROFILE ###
  strapi-local-service:
    extends:
      service: strapi-service
    profiles: ["local"]
    command: npm run strapi:develop
    environment:
      NODE_ENV: development
    ports:
      - "1337:1337"
    volumes:
      - ./config:/opt/app/config
      - ./public/uploads:/opt/app/public/uploads

  ### REMOTE PROFILE ###
  strapi-remote-service:
    extends:
      service: strapi-service
    profiles: ["remote"]
    command: npm run strapi:develop
    environment:
      NODE_ENV: development
    ports:
      - "1337:1337"
    volumes:
      - strapi-volume-uploads:/opt/app/public/uploads

  ### PROD PROFILE ###
  strapi-prod-service:
    extends:
      service: strapi-service
    profiles: ["prod"]
    command: npm run strapi:start
    environment:
      NODE_ENV: production
    ports:
      - "1337:1337"
    volumes:
      - strapi-volume-uploads:/opt/app/public/uploads

volumes:
  strapi-volume-pg_data:
  strapi-volume-uploads:

networks:
  strapi-network:
    name: strapi-network
    driver: bridge

