services:
  strapi:
    container_name: viscera
    build: .
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 1337
      APP_KEYS: "toBeModified1,toBeModified2"
      API_TOKEN_SALT: tobemodified
      ADMIN_JWT_SECRET: tobemodified
      TRANSFER_TOKEN_SALT: tobemodified
      JWT_SECRET: tobemodified
    ports:
      - "1337:1337"
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        target: /app/node_modules
    depends_on:
      - db

  db:
    container_name: viscera-db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
