services:
  strapi:
    container_name: strapi
    build: .
    image: strapi-local:latest
    restart: unless-stopped
    environment:
      DATABASE_HOST: strapiDB
      NODE_ENV: development
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_SIGNED_URL_EXPIRES: ${AWS_SIGNED_URL_EXPIRES}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - strapiDB

volumes:
  strapi-pg_data:

networks:
  strapi:
    name: strapi
    driver: bridge