services:
  strapi:
    environment:
      NODE_ENV: development
    volumes:
      - ./config:/opt/app/config
      # - ./src:/opt/app/src
      # - ./package.json:/opt/package.json
      - ./public/uploads:/opt/app/public/uploads
    command: npm run strapi:develop