services:
  strapi:
    extends:
      file: ../docker-compose.yml
      service: strapi
    # Override command to ensure container stays running
    command: sleep infinity
    environment:
      # Additional dev-specific environment variables can be added here
      NODE_ENV: development
    volumes:
      - type: bind
        source: ..
        target: /app
      - type: volume
        target: /app/node_modules
      - type: volume
        target: /app/.cache
      - type: volume
        target: /app/build

  db:
    extends:
      file: ../docker-compose.yml
      service: db

volumes:
  pgdata:
