services:
  strapi:
    extends:
      file: ../docker-compose.yml
      service: strapi
    container_name: strapi_devcontainer
    command: sleep infinity
    env_file:
      - ../.env
      - .env.devcontainer
    volumes:
      - type: bind
        source: ..
        target: /opt/app
      - type: volume
        target: /opt/app/node_modules
      - type: volume
        target: /opt/app/.cache
      - type: volume
        target: /opt/app/build

  strapiDB:
    extends:
      file: ../docker-compose.yml
      service: strapiDB
    container_name: strapiDB_devcontainer
    env_file: ../.env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-strapi}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-strapi}
      POSTGRES_DB: ${DATABASE_NAME:-strapi}
    ports:
      - "5433:5432"

volumes:
  strapi-data:

networks:
  strapi:
    name: strapi
    driver: bridge
