services:
  strapi:
    extends:
      file: ../docker-compose.yml
      service: strapi
    # Override command to ensure container stays running
    command: sleep infinity
    env_file: ../.env
    environment:
      # Additional dev-specific environment variables can be added here
      NODE_ENV: development
    volumes:
      - type: bind
        source: ..
        target: /opt/app
      - type: volume
        target: /opt/app/node_modules
      - type: volume
        target: /opt/app/.cache
      - type: volume
        target: /opt/app/build

  strapiDB:
    extends:
      file: ../docker-compose.yml
      service: strapiDB
    env_file: ../.env

volumes:
  strapi-data:


networks:
  strapi_net:
    external: true