version: '3'

services:
  strapi:
    extends:
      file: ../docker-compose.yml
      service: strapi
    # Override command to ensure container stays running
    command: sleep infinity
    environment:
      # Additional dev-specific environment variables can be added here
      NODE_ENV: development
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/.cache
      - /app/build

  db:
    extends:
      file: ../docker-compose.yml
      service: db
